# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\CSU\Documents\CommandFramework\DevBranch\Applications\METECControl\GUI\DesignerWidgets\uiWidgets\ExperimentInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(876, 189)
        Frame.setMinimumSize(QtCore.QSize(876, 189))
        Frame.setMaximumSize(QtCore.QSize(876, 189))
        Frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Frame.setFrameShape(QtWidgets.QFrame.Box)
        Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        Frame.setLineWidth(2)
        Frame.setMidLineWidth(1)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Frame)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 161))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 161))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Frame", "GSH-1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Frame", "GSH-2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Frame", "GSH-3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Frame", "GSH-4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "Test_Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "N_Iterations"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "Cur_Iter"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "Cur_Iter_Time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Frame", "Min_per_Iter"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Frame", "Progress"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Frame", "Elapsed_Time"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Frame", "Total_Time"))
